src/posts/urls.py
from django.urls import path
from posts.views import (
    post_list,
    post_add_view,
    post_edit_view,
    post_delete_view,
    post_home,
    post_detail_view,
)


app_name = "posts"
urlpatterns = [
    path("", post_home, name="posthome"),
    path("posts-list/", post_list, name="postslist"),
    path("posts-add/", post_add_view, name="posts_add"),
    path("posts/<int:postid>/", post_detail_view, name="posts_detail"),
    path("posts-edit/<int:postid>", post_edit_view, name="posts_edit"),
    path("post-delete/", post_delete_view, name="posts_delete"),
]

src/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("user/", include("useraccount.urls", namespace="user")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/useraccount/urls.py
from django.urls import path
from useraccount.views import UserLoginView, SignupView, user_profile, user_profile_edit
from django.contrib.auth.views import LogoutView

app_name = "user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", SignupView.as_view(), name="register"),
    path("profile/<user>/userid=<int:id>/", user_profile, name="userprofile"),
    path("profile-edit/<int:id>", user_profile_edit, name="edit_profile"),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if title %}
            {{title}}
        {% else %}
        Social
        {% endif %}
      
    </title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/kk.png' %}"/>
    {% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/login.css'%}">


    {% endblock stylesheet %}
</head>
<body>
   
    <div class="container">
        {% block content %} 

        {% endblock content %}
    </div>
    {% block script %}
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/jqueryajax.min.js'%}"></script>
    <script src="{% static 'js/bs.min.js'%}"></script>


    {% endblock script %}
</body>
</html>

src/templates/base_site.html
{% extends 'base.html' %}

{% block content %} 
    {% include 'navbar.html' %}
    {% block maincontent %}
    
    {% endblock maincontent %}
{% endblock content %}

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-name">

  <div class="inline">
    {%load static%}
    <img class="logo" src="{% static 'images/kk.png' %}" alt="">
   </div>
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'posts:posthome' %}">Home</a>
          </li>
        
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:posts_add' %}">Add posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:postslist' %}">List posts</a>
          </li>
          <li class="nav-item"> 
              <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link" href="{% url 'user:userprofile' user.username user.id %}">My Profile</a>
        </li>
        
          {% endif %}
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">Login</a>
      
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'user:register' %}">Register</a>
      
          </li>
          {% endif %}
    </ul>
    </div>
</div>

    </div>
    </nav>
  