src/posts/urls.py
from django.urls import path
from posts.views import (
    post_list,
    post_add_view,
    post_edit_view,
    post_delete_view,
    post_home,
    post_detail_view,
)


app_name = "posts"
urlpatterns = [
    path("", post_home, name="posthome"),
    path("posts-list/", post_list, name="postslist"),
    path("posts-add/", post_add_view, name="posts_add"),
    path("posts/<int:postid>/", post_detail_view, name="posts_detail"),
    path("posts-edit/<int:postid>", post_edit_view, name="posts_edit"),
    path("post-delete/", post_delete_view, name="posts_delete"),
]

src/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("user/", include("useraccount.urls", namespace="user")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/useraccount/urls.py
from django.urls import path
from useraccount.views import UserLoginView, SignupView, user_profile, user_profile_edit
from django.contrib.auth.views import LogoutView

app_name = "user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", SignupView.as_view(), name="register"),
    path("profile/<user>/userid=<int:id>/", user_profile, name="userprofile"),
    path("profile-edit/<int:id>", user_profile_edit, name="edit_profile"),
]

src/useraccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    address = models.CharField(max_length=255, blank=True, null=True)
    contact = models.CharField(max_length=255, blank=True, null=True)


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    profile_picture = models.ImageField(
        upload_to="profile_images", blank=True, null=True
    )
    about = models.CharField(max_length=1000, blank=True)
    location = models.CharField(max_length=100, blank=True)

src/useraccount/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from useraccount.models import Profile
from betterforms.multiform import MultiModelForm


User = get_user_model()


class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "username",
            "password1",
            "password2",
            "address",
            "contact",
        )


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "email",
            "username",
            "address",
            "contact",
        )


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            "profile_picture",
            "location",
            "about",
        )

src/useraccount/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from useraccount.forms import UserSignupForm, UserProfileForm, UserEditForm
from useraccount.models import Profile, User
from django.http import HttpResponseRedirect


# Create your views here.
User = get_user_model()


class UserLoginView(LoginView):
    template_name = "login.html"
    redirect_authenticated_user = True


class SignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = "register.html"
    success_url = reverse_lazy("posts:posthome")


@login_required
def user_profile(request, user, id):
    user = get_object_or_404(User, username=user, id=id)
    print(user)

    profile = get_object_or_404(Profile, user=user)
    print(profile.profile_picture)

    return render(
        request,
        "profile.html",
        {"users": user, "profile": profile},
    )


@login_required
def user_profile_edit(request, id):
    user = get_object_or_404(User, id=id, username=request.user)
    print(user)
    user_profiles = get_object_or_404(Profile, user__id=id)
    print(user_profile)
    # user_profile = Profile.objects.filter(id=id)
    # user = User.objects.filter(id=id)
    # print("LEngth", user[0].user.username)
    # for i in user:
    #     print("asdasdasd", i.about)
    # print("user rohsan", user[0])

    # # try:
    # #     Posts.objects.get(id=postid)
    # # except Posts.DoesNotExist:
    # #     raise Http404()  import HTTp404 first

    form = UserProfileForm(
        request.POST or None, request.FILES or None, instance=user_profiles
    )
    userss = UserEditForm(request.POST or None, request.FILES or None, instance=user)
    if form.is_valid() and userss.is_valid():
        userss.save()
        form.save()
        return HttpResponseRedirect(
            reverse(
                "user:userprofile",
                args=(
                    user.username,
                    user.id,
                ),
            )
        )

    return render(request, "profile_edit.html", {"form": form, "user": userss})

src/useraccount/templates/login.html
{% extends 'base.html' %}

{% block content %}
<center>Welcome To KuraKani</center>
<div class="wrapper">
    <div class="logologin">
        {% load static %}
        <img src="{% static 'images/kk.png' %}" alt="">
    </div>
  
    <form method="post" class="p-3 mt-3">{% csrf_token %}
        {{ form.non_field_errors }}
        
        <div class="form-field d-flex align-items-center">
            {{ form.username.errors }}

            <span class="far fa-user"></span>
            {{ form.username }}

            <!-- <input type="text" name="userName" id="userName" placeholder="Username"> -->
        </div>
        <div class="form-field d-flex align-items-center">
            {{ form.password.errors }}

            <span class="fas fa-key"></span>
            {{ form.password }}

            <!-- <input type="password" name="password" id="pwd" placeholder="Password"> -->
        </div>

        <button class="btn mt-3">Login</button>
    </form>
    <div class="text-center fs-6">
        <a href="#">Forget password?</a> or <a href="#">Sign up</a>
    </div>
</div>

{% endblock content %}

src/useraccount/templates/profile.html
{% extends 'base_site.html' %} 
{% block maincontent %}
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
  <div class="card p-4">
    <div class="image d-flex flex-column justify-content-center align-items-center">
      <a class="btn ">
        {% if profile.profile_picture %}
        <img src="{{ profile.profile_picture.url }}" alt="image" class="img-responsive w-100"></a>
        {% else %}
        {% load static %}
        <img src="{% static 'images/user.png' %}" alt="default image" class="img-responsive w-100"></a>
        
        {% endif %}
      
        </a>
      <span class="name mt-3">{{users.first_name }} {{ users.last_name}}</span>
      <span class="idd">@{{users.username}}</span>
      <div class="d-flex flex-row justify-content-center align-items-center gap-2">
        <span class="idd1">Oxc4c16a645_b21a</span>
        <span><i class="fa fa-copy"></i></span>
      </div>
      <div class="d-flex flex-row justify-content-center align-items-center mt-3">
        <span class="number">1069 <span class="follow">Followers</span></span>
      </div>
      <div class="d-flex mt-2">
        <button class="btn btn-dark"><a href="{% url 'user:edit_profile' user.id%}">Edit Profile</a></button>
      </div>
      <div class="text mt-3">
        <span
          >Eleanor Pena is a creator of minimalistic x bold graphics and digital
          artwork.<br /><br />
          Artist/ Creative Director by Day #NFT minting@ with FND night.
        </span>
      </div>
      <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center" >
        <span><i class="fa fa-twitter"></i></span>
        <span><i class="fa fa-facebook-f"></i></span>
        <span><i class="fa fa-instagram"></i></span>
        <span><i class="fa fa-linkedin"></i></span>
      </div>
      <div class="px-2 rounded mt-4 date">
        <span class="join">Joined May,2021</span>
      </div>
    </div>
  </div>
</div>
{% endblock maincontent %}

src/useraccount/templates/profile_edit.html
{% extends 'base.html' %}
{% block content %}
<center>
  
<form method="POST">  {% csrf_token %}
  
    {{ form.non_field_errors }}
    {% for user in user%}
     <div class="form-group my-2">
        <label> {{user.label_tag}}</label>
        {{ user }}
        <span class="text text-danger">{{ user.errors }}</span>
    
   
    {% endfor %}


    {% for field in form%}
     <div class="form-group my-2">
        <label> {{field.label_tag}}</label>
        {{ field }}
        <span class="text text-danger">{{ field.errors }}</span>
    
   
    {% endfor %}
</form>
    <input type="submit" class="btn btn-primary" value="Submit">
</form>

</center>

{% endblock content %}

src/useraccount/templates/register.html
{% extends 'base.html' %}
{% block content %}
<center>
  
<form method="POST">  {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form%}
     <div class="form-group my-2">
        <label> {{field.label_tag}}</label>
        {{ field }}
        <span class="text text-danger">{{ field.errors }}</span>
    
    </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="Sign Up">
</form>
<a href="{% url 'user:login' %}">Login</a>
</center>

{% endblock content %}