src/posts/urls.py
from django.urls import path
from posts.views import (
    post_list,
    post_add_view,
    post_edit_view,
    post_delete_view,
    post_home,
    post_detail_view,
)


app_name = "posts"
urlpatterns = [
    path("", post_home, name="posthome"),
    path("posts-list/", post_list, name="postslist"),
    path("posts-add/", post_add_view, name="posts_add"),
    path("posts/<int:postid>/", post_detail_view, name="posts_detail"),
    path("posts-edit/<int:postid>", post_edit_view, name="posts_edit"),
    path("post-delete/", post_delete_view, name="posts_delete"),
]

src/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls", namespace="posts")),
    path("user/", include("useraccount.urls", namespace="user")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/models.py
from django.db import models
from useraccount.models import User


# Create your models here.
class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Posts(TimeStamp):

    description = models.TextField(max_length=65535, blank=True, null=True)
    image = models.ImageField(upload_to="images", blank=True, null=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title

src/posts/forms.py
from django import forms
from posts.models import Posts


class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        # fields = "__all__"
        exclude = ("created_by",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields["name"].widget.attrs["class"] = "form-control"   this is used to customize single field
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    def clean_name(self):
        title = self.cleaned_data.get("title")
        if title.isdigit():
            raise forms.ValidationError("Title cannot be a number")
        return title

src/posts/views.py
from django.shortcuts import render, get_object_or_404
from posts.models import Posts
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from posts.forms import PostsForm
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse


# Create your views here.
@login_required
def post_list(request):
    posts = Posts.objects.all().order_by("-id")
    return render(request, "list_posts.html", {"post": posts})


@login_required
def post_add_view(request):
    form = PostsForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        rep = form.save(commit=False)
        rep.created_by = request.user
        rep.save()
        return HttpResponseRedirect(reverse("posts:postslist"))
    return render(
        request, "add_post.html", {"form": form}
    )  # the dictionary key is passed in form in html file


@login_required
def post_edit_view(request, postid):
    post = get_object_or_404(Posts, id=postid)
    # try:
    #     Posts.objects.get(id=postid)
    # except Posts.DoesNotExist:
    #     raise Http404()  import HTTp404 first
    form = PostsForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("posts:posts"))

    return render(request, "add_post.html", {"form": form})


@login_required
def post_delete_view(request):
    postid = request.POST.get("postsid")
    posts = get_object_or_404(Posts, id=postid)
    posts.delete()
    return HttpResponseRedirect(reverse("posts:postslist"))


@login_required
def post_home(request):
    posts = Posts.objects.all().order_by("-id")

    paginator = Paginator(posts, per_page=4)
    page_number = request.GET.get("page")
    try:
        page_obj = paginator.get_page(page_number)  # returns the desired page object
    except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # if page is empty then return last page
        page_obj = paginator.page(paginator.num_pages)
    return render(request, "allpost.html", {"form": page_obj})


@login_required
def post_detail_view(request, postid):
    post = get_object_or_404(Posts, id=postid)
    return render(request, "post_detail.html", {"form": post})

src/posts/templates/add_post.html
{% extends 'base_site.html' %}

{% block maincontent %}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{form.media}}
    {{ form.non_field_errors }}
    {% for field in form%}
     <div class="form-group my-2">
        <label> {{field.label_tag}}</label>
        {{ field }}
        <span class="text text-danger">{{ field.errors }}</span>
    </div>
    {% endfor %}
    <div class="form-group my-2">
    
        <label> User:</label>
        <input class="form-control" type="text" readonly value="{{ request.user }}">
    </div>
    <input type="submit" name="Submit" class="btn btn-primary" value="Submit" id="">
</form>
{% endblock maincontent %}

src/posts/templates/allpost.html
{% extends 'base_site.html' %}

{% block maincontent %} 

<section class="news pt-0">
  <div class="container mt-md-5">
    <!-- <h2 class="mx-4 my-0 text-center">Recent News</h2> -->
    <ul class="row d-lg-flex list-unstyled image-block justify-content-center px-lg-0 mx-lg-0">
{% for posts in form %}

      <li class="col-lg-4 col-md-5 image-block full-width p-3">
        <div class="image-block-inner">
          <a class="mh-100" href="{% url 'posts:posts_detail' posts.id %}">
            {% if posts.image %}
            <img src="{{ posts.image.url }}" alt="image" class="img-responsive w-100"></a>
            {% else %}
            {% load static %}
            <img src="{% static 'images/kurakani.png' %}" alt="default image" class="img-responsive w-100"></a>
            
            {% endif %}
          <span class="hp-posts-cat">{{posts.title}}</span>
          <!-- <span class="reporter">By {{posts.reporter}}</span> -->

          <h4 class="mt-3"><a href="{% url 'posts:posts_detail' posts.id %}">{{posts.description|truncatewords:10}}</a></h4>
          <!--  <p></p> -->
          <a href="{% url 'posts:posts_detail' posts.id %}" class="read-more">Read more</a>
        </div><!-- .image-block-inner -->
      </li>
{% endfor %}
    </ul>
  </div>
  <center>
  

    {% if form.has_previous %}

    <a href="?page={{form.previous_page_number}}">

      <button type="button" class="btn btn-primary btn-sm">Previous Page</button>

    </a>

{% endif%}

{% if form.has_next %}

    <a href="?page={{form.next_page_number}}">

      <button type="button" class="btn btn-secondary btn-sm">Next Page</button>

    </a>

{% endif%}
  </center>
</section>

{% endblock maincontent %}

src/posts/templates/list_posts.html
{% extends 'base_site.html' %}

{% block maincontent %} 
<h1>posts List</h1>
<table class="table table-bordered table-hover">
<thead>
   <tr>
    
    <th>Description</th>
   <th>Action</th>

   </tr>
</thead>
   {% for posts in post %}
<tbody>
   <tr>
   
    <td><a href="{% url 'posts:posts_edit' posts.id %}">{{posts.description}}</a></td>
   
   
  <td>
<button data-postsid="{{posts.id}}" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Delete
 </button>
  </td>
   </tr>
   {% endfor %}
</tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
         <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
       </div>
       <div class="modal-body">
         Are You Sure You Want to delete this posts?
         <form id="deleteform" method="post" action="{% url 'posts:posts_delete' %}">{% csrf_token %}
            <input type="hidden" name="postsid" id="_postsid">
         </form>
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
         <button id="deletebutton" type="submit" class="btn btn-danger">Yes</button>
       </div>
     </div>
   </div>
 </div>

{% endblock maincontent %}
{% block script%}
{{ block.super }}
<script type="text/javascript">
   $(document).ready(function()
   {
      $.ajax({
         url:'/demo-for-ajax',
         type:'GET',
         dataType:'json',
         success:function(res){
            console.log(res);
         },
         error:function(res){
            console.log(res);
         }
      });

      let modal=document.getElementById("exampleModal");
      modal.addEventListener("show.bs.modal",function(evt){
         let btn=evt.relatedTarget;
         let postsid=btn.dataset.postsid;
         $("#_postsid").val(postsid);
      });
      $("#deletebutton").click(function(){
         $("#deleteform").submit();
      })
   });
   </script>
{% endblock script %}

src/posts/templates/post_detail.html
{% extends 'base_site.html' %}

{% block maincontent %} 

<div class="image-block-inner">
    
      {% if form.image %}
      <img src="{{ form.image.url }}" alt="{{ form.title }}" height="350px" class="img-responsive w-100">
      {% else %}
      <img src="https://images.pexels.com/photos/14651941/pexels-photo-14651941.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="default image" height="300px" class="img-responsive w-100">
      
      {% endif %}

    <!-- <span class="reporter">{{form.reporter}}</span> -->

    <h4 class="mt-3">{{form.description}</a></h4>
    <!--  <p></p> -->
   
  </div><!-- .image-block-inner -->
{% endblock maincontent %}